# Generated by Django 3.2.13 on 2023-04-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0003_auto_20230417_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=False)),
                ('useraccess', models.CharField(max_length=255)),
                ('passphrase', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employees')),
            ],
            options={
                'db_table': 'UserAccount',
            },
        ),
    ]
