# Generated by Django 2.1.15 on 2023-05-15 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.CharField(choices=[('Administrator', 'Administrator'), ('Employees', 'Employees')], default='Employees', max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('useraccess', models.CharField(max_length=255)),
                ('passphrase', models.TextField()),
                ('salt', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Employees')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
