# Generated by Django 3.2.13 on 2023-04-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='passphrase',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='useraccess',
            new_name='username',
        ),
    ]
