# Generated by Django 3.2.13 on 2023-04-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20230419_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='password',
            new_name='passphrase',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='username',
            new_name='useraccess',
        ),
    ]
