# Generated by Django 3.2.13 on 2023-04-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('suffix', models.CharField(blank=True, max_length=200, null=True)),
                ('Birthday', models.DateField(null=True)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('is_Regular', models.BooleanField(default=False)),
                ('RegularizationDate', models.DateField(null=True)),
                ('EmploymentDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('lunch_break_start', models.TimeField()),
                ('lunch_break_end', models.TimeField()),
                ('created_by', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employees')),
            ],
            options={
                'db_table': 'WorkSchedule',
            },
        ),
    ]
