# Generated by Django 2.1.15 on 2023-05-15 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True, verbose_name='First Name: ')),
                ('middlename', models.CharField(max_length=255, null=True, verbose_name='Middle Name: ')),
                ('lastname', models.CharField(max_length=255, null=True, verbose_name='Last Name: ')),
                ('suffix', models.CharField(max_length=255, null=True, verbose_name='Suffix: ')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.CharField(max_length=255, null=True, verbose_name='Gender: ')),
                ('civilstatus', models.CharField(max_length=255, null=True, verbose_name='Civil Status: ')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date: ')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Data: ')),
                ('isRegular', models.BooleanField(default=False)),
                ('RegularizationDate', models.DateField(null=True)),
                ('EmploymentDate', models.DateField(null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('lunch_break_start', models.TimeField()),
                ('lunch_break_end', models.TimeField()),
                ('created_by', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkSchedules', to='Employees.Employees')),
            ],
            options={
                'db_table': 'WorkSchedules',
            },
        ),
    ]
