# Generated by Django 4.1.7 on 2023-04-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='employees',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workschedule_set', to='Employees.employees'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
    ]
