# Generated by Django 3.2.13 on 2023-04-17 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_remove_workschedule_employees_workschedule_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='is_Regular',
            new_name='isRegular',
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workschedules', to='Employees.employees'),
        ),
    ]
